version: '3.8'

services:
  devidian-tv-ingest:
    container_name: devidian-tv_ingest
    image: devidian/devidian-tv-transcoder:latest
    restart: unless-stopped
    ports:
      - 1935:1935
      - 8080:80
      - 8443:443
    networks:
      - dtvnet
    links:
      - devidian-tv-api:dtv-auth
    environment:
      HTTP_PORT: ${INGEST_HTTP_PORT}
      RTMP_PORT: ${INGEST_RTMP_PORT}
      STREAM_PUBLISH_NOTIFY_URL: ${INGEST_PUBLISH_NOTIFY_URL}
      RTMP_TRANSCODE_IP: ${INGEST_RTMP_TRANSCODE_IP}
      RTMP_HLS_IP: ${INGEST_RTMP_HLS_IP}
    volumes:
      - /appdata/nginx/certs:/opt/certs

  devidian-tv-app:
    container_name: devidian-tv_app
    image: devidian/devidian-tv-app:latest
    restart: unless-stopped
    ports:
      - 8090:80

  devidian-tv-api:
    container_name: devidian-tv_api
    image: devidian/devidian-tv-api:latest
    restart: unless-stopped
    depends_on:
      - devidian-tv-mongo
    ports:
      - 8091:80
    networks:
      - dtvnet
    links:
      - devidian-tv-mongo:dtv-db
    environment: 
      MONGODB_URI: ${API_MONGODB_URI}
      MONGODB_DB: ${API_MONGODB_DB}
      MONGO_APPNAME: ${API_MONGO_APPNAME}
      SENDGRID: ${API_SENDGRID}
      MAIL_FROM: ${API_MAIL_FROM}
      MAIL_SUBJECT_VERIFICATION: ${API_MAIL_SUBJECT_VERIFICATION}
      MAIL_SUBJECT_WELCOME: ${API_MAIL_SUBJECT_WELCOME}
      MAIL_SUBJECT_BETA: ${API_MAIL_SUBJECT_BETA}
      OID_REALM: ${API_OID_REALM}
      OID_STEAM_REDIRECT: ${API_OID_STEAM_REDIRECT}
      OID_STEAM_KEY: ${API_OID_STEAM_KEY}
      OID_STEAM_RETURN: ${API_OID_STEAM_RETURN}
      COOKIE_DOMAIN: ${API_COOKIE_DOMAIN}
      PORT: ${API_PORT}
      HOST: ${API_HOST}
      TRANSCODER_IP: ${AUTH_TRANSCODER_IP}
      TRANSCODER_TYPE: ${AUTH_TRANSCODER_TYPE}
      APP_LOG_LEVEL: ${API_APP_LOG_LEVEL}
      APP_LOG_COLOR: ${API_APP_LOG_COLOR}
      APP_LOG_DB: ${API_APP_LOG_DB}
      APP_LOG_WS: ${API_APP_LOG_WS}

  devidian-tv-mongo:
    container_name: devidian-tv_mongodb
    image: mongo
    restart: always
    volumes:
      - /appdata/mongodata:/data/db
    hostname: mongohost
    ports:
      - 27117:27017
    networks:
      - dtvnet
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

  
networks:
  dtvnet: